Repository fun-sports-training-games-organization/fstg-web-app, pull requests merged in 2022-01, with the labels that each got.

#130 Feature/do workout #58 albert
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  src/components/atoms/loader/Loader.tsx
  src/components/atoms/pause-play-button/PausePlayButton.tsx
  src/components/atoms/unlock-lock-button/UnlockLockButton.tsx
  src/components/molecules/actions-menu/ActionsMenu.tsx
  src/components/molecules/countdown-timer/CountdownTimer.tsx
  src/components/molecules/edit-image/EditImage.tsx
  src/components/molecules/exercise-item/ExerciseItem.tsx
  src/components/molecules/exercises-or-reps-icon/ExercisesOrRepsIcon.tsx
  src/components/molecules/manage-workout-exercises/ManageWorkoutExercises.tsx
  src/components/molecules/page-title-action/PageTitleAction.tsx
  src/components/molecules/reps-icon/RepsIcon.tsx
  src/components/molecules/time-icon/TimeIcon.tsx
  src/components/organisms/create-edit-exercise-form/CreateEditExerciseForm.tsx
  src/components/organisms/exercises-content/ExercisesContent.tsx
  src/components/organisms/exercises-time-reps-icons/ExercisesTimeRepsIcons.tsx
  src/components/pages/exercises/manage/ManageExercises.tsx
  src/components/pages/workouts/do/DoWorkout.tsx
  src/components/pages/workouts/edit/EditWorkout.tsx
  src/components/pages/workouts/manage/ManageWorkouts.tsx
  src/components/pages/workouts/start/StartWorkout.tsx
  src/index.css
  src/model/ActionMenuOption.model.ts
  src/model/Exercise.model.ts
  src/util/exercise-util.ts
  src/util/workout-util.ts
Labels: bug, enhancement, 3

#134 Bugfix/exercise workout settings albert
  src/components/atoms/submit-button/SubmitButton.tsx
  src/components/molecules/manage-workout-exercises/ManageWorkoutExercises.tsx
  src/components/organisms/create-edit-exercise-form/CreateEditExerciseForm.tsx
  src/components/organisms/responsive-dialog/ResponsiveDialog.tsx
  src/components/pages/exercises/manage/ManageExercises.tsx
  src/components/pages/workouts/edit/EditWorkout.tsx
  src/hooks/useEntityManager.ts
  src/model/Basics.model.ts
  src/model/Exercise.model.ts
  src/model/Workout.model.ts
  src/util/exercise-util.ts
  src/util/workout-util.ts
Labels: bug, 3

#133 Finished implementing Blank Slate Design
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  src/assets/dumbbells.png
  src/assets/exercise.png
  src/assets/workout.png
  src/components/organisms/responsive-container/ResponsiveContainer.tsx
  src/components/pages/exercises/manage/ManageExercises.tsx
  src/components/pages/workouts/manage/ManageWorkouts.tsx
  src/components/templates/blank-slate/BlankSlate.tsx
  src/components/templates/blank-slate/BlankSlate.types.ts
  src/hooks/useEntityManager.ts
  src/hooks/useFileManager.ts
  src/routes/Routes.ts
  src/util/navigation-util.ts
Labels: bug, enhancement

#135 Feature/do workout continue #58 albert
  src/components/molecules/countdown-timer/CountdownTimer.tsx
  src/components/molecules/page-title-action/PageTitleAction.tsx
  src/components/organisms/do-workout-item/DoWorkoutItem.tsx
  src/components/pages/workouts/do/DoWorkout.tsx
Labels: 1

#136 Feature/do workout continue #58 albert
  src/components/molecules/page-title-action/PageTitleAction.tsx
  src/components/pages/workouts/do/DoWorkout.tsx
Labels: 1

#137 Feature/do workout continue #58 albert
  package-lock.json
  package.json
  src/components/organisms/do-workout-item/DoWorkoutItem.tsx
  src/components/pages/workouts/do/DoWorkout.tsx
  src/util/date-util.ts
  src/util/exercise-util.ts
Labels: 2

#138 Feature/do workout continue #58 albert
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  src/components/molecules/countdown-timer/CountdownTimer.tsx
  src/components/pages/workouts/do/DoWorkout.tsx
  src/model/Exercise.model.ts
  src/util/date-util.ts
  src/util/notifications-util.ts
Labels: enhancement, 2

#139 get scroll to current exercise working, move snackbars up a little bi…
  src/components/pages/workouts/do/DoWorkout.tsx
  src/index.css
  src/util/exercise-util.ts
Labels: enhancement, 2

#150 Feature/do workout continue #58 albert
  package-lock.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  src/components/atoms/time-or-count-field/TimeOrCountField.tsx
  src/components/molecules/inputs/time-field/TimeField.tsx
  src/components/organisms/dialogs/responsive-dialog/ResponsiveDialog.test.tsx
  src/components/organisms/dialogs/responsive-dialog/ResponsiveDialog.tsx
  src/components/organisms/dialogs/responsive-dialog/ResponsiveDialog.types.ts
  src/components/organisms/forms/create-edit-exercise-form/CreateEditExerciseForm.tsx
  src/components/pages/dashboard/Dashboard.tsx
  src/components/pages/legal/PrivacyPolicyPage.tsx
  src/components/pages/legal/TermsOfServicePage.tsx
  src/components/pages/workouts/do/DoWorkout.tsx
  src/model/Basics.model.ts
  src/model/Exercise.model.ts
  src/model/Workout.model.ts
Labels: 5

#158 Bugfix/time based enter result #124 albert
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  src/components/atoms/time-or-count-field/TimeOrCountField.tsx
  src/components/molecules/display-workout-exercises/DisplayWorkoutExercises.tsx
  src/components/molecules/exercise-item/ExerciseItem.tsx
  src/components/molecules/inputs/time-field/TimeField.tsx
  src/components/molecules/manage-workout-exercises/ManageWorkoutExercises.tsx
  src/components/organisms/do-workout-item/DoWorkoutItem.tsx
  src/components/organisms/forms/create-edit-exercise-form/CreateEditExerciseForm.tsx
  src/components/pages/exercises/manage/ManageExercises.tsx
  src/components/pages/workouts/do/DoWorkout.tsx
  src/components/templates/cards/exercise-card/ExerciseCardItem.tsx
  src/components/templates/cards/statistics-card/StatisticsCard.tsx
  src/index.css
  src/model/Basics.model.ts
Labels: 2

#159 add exercise related italian translations
  public/locales/it/translation.json
Labels: enhancement, 1

#157 You can now start a workout directly from the dashboard
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/it/translation.json
  src/components/molecules/manage-workout-exercises/ManageWorkoutExercises.tsx
  src/components/pages/workouts/edit/EditWorkout.tsx
  src/components/templates/cards/exercise-card/ExerciseCard.tsx
  src/components/templates/cards/workout-card/WorkoutCard.tsx
  src/components/templates/cards/workout-card/WorkoutCardItem.tsx
Labels: enhancement, 1

#160 switch route from do workout to start workout because this is where t…
  src/components/templates/cards/workout-card/WorkoutCardItem.tsx
Labels: enhancement, 1

#162 records workings correctly on statistics now
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/locales/it/translation.json
  src/components/App.tsx
  src/components/molecules/not-yet-implemented-dialog/NotYetImplementedDialog.tsx
  src/components/pages/statistics-dashboard/StatisticsDashboard.tsx
  src/components/pages/workouts/do/DoWorkout.tsx
  src/components/templates/cards/record-card/RecordCard.tsx
  src/components/templates/cards/record-card/RecordCardItem.tsx
  src/routes/Routes.ts
  src/util/workout-util.ts
Labels: enhancement, 2

#169 Workout results review dialog bug
  src/components/pages/workouts/do/DoWorkout.tsx
Labels: bug, 1
